/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chris_eban_common_ZipUtils */

#ifndef _Included_com_chris_eban_common_ZipUtils
#define _Included_com_chris_eban_common_ZipUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chris_eban_common_ZipUtils
 * Method:    executeCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_chris_eban_common_ZipUtils_executeCommand
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
